/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package draughtsoop;

import draughtsoop.chess.Chess;
import draughtsoop.draughts.Draughts;
import java.util.Arrays;

/**
 *
 * @author James.Fennell
 */
public class BoardGame extends javax.swing.JFrame {

    /**
     * Creates new form Draughts
     */
    public BoardGame() {
        initComponents();
        newGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardPanel = new javax.swing.JPanel();
        square1 = new javax.swing.JButton();
        square2 = new javax.swing.JButton();
        square3 = new javax.swing.JButton();
        square4 = new javax.swing.JButton();
        square5 = new javax.swing.JButton();
        square6 = new javax.swing.JButton();
        square7 = new javax.swing.JButton();
        square8 = new javax.swing.JButton();
        square9 = new javax.swing.JButton();
        square10 = new javax.swing.JButton();
        square11 = new javax.swing.JButton();
        square12 = new javax.swing.JButton();
        square13 = new javax.swing.JButton();
        square14 = new javax.swing.JButton();
        square15 = new javax.swing.JButton();
        square16 = new javax.swing.JButton();
        square17 = new javax.swing.JButton();
        square18 = new javax.swing.JButton();
        square19 = new javax.swing.JButton();
        square20 = new javax.swing.JButton();
        square21 = new javax.swing.JButton();
        square22 = new javax.swing.JButton();
        square23 = new javax.swing.JButton();
        square24 = new javax.swing.JButton();
        square25 = new javax.swing.JButton();
        square26 = new javax.swing.JButton();
        square27 = new javax.swing.JButton();
        square28 = new javax.swing.JButton();
        square29 = new javax.swing.JButton();
        square30 = new javax.swing.JButton();
        square31 = new javax.swing.JButton();
        square32 = new javax.swing.JButton();
        square33 = new javax.swing.JButton();
        square34 = new javax.swing.JButton();
        square35 = new javax.swing.JButton();
        square36 = new javax.swing.JButton();
        square37 = new javax.swing.JButton();
        square38 = new javax.swing.JButton();
        square39 = new javax.swing.JButton();
        square40 = new javax.swing.JButton();
        square41 = new javax.swing.JButton();
        square42 = new javax.swing.JButton();
        square43 = new javax.swing.JButton();
        square44 = new javax.swing.JButton();
        square45 = new javax.swing.JButton();
        square46 = new javax.swing.JButton();
        square47 = new javax.swing.JButton();
        square48 = new javax.swing.JButton();
        square49 = new javax.swing.JButton();
        square50 = new javax.swing.JButton();
        square51 = new javax.swing.JButton();
        square52 = new javax.swing.JButton();
        square53 = new javax.swing.JButton();
        square54 = new javax.swing.JButton();
        square55 = new javax.swing.JButton();
        square56 = new javax.swing.JButton();
        square57 = new javax.swing.JButton();
        square58 = new javax.swing.JButton();
        square59 = new javax.swing.JButton();
        square60 = new javax.swing.JButton();
        square61 = new javax.swing.JButton();
        square62 = new javax.swing.JButton();
        square63 = new javax.swing.JButton();
        square64 = new javax.swing.JButton();
        gameInfojLabel = new javax.swing.JLabel();
        newGamejButton = new javax.swing.JButton();
        gameInfojLabel2 = new javax.swing.JLabel();
        gameInfoLabel3 = new javax.swing.JLabel();
        gameSelectJComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boardPanel.setLayout(new java.awt.GridLayout(8, 8));

        square1.setText(" ");
        square1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square1MouseReleased(evt);
            }
        });
        boardPanel.add(square1);

        square2.setBackground(new java.awt.Color(153, 153, 153));
        square2.setText(" ");
        square2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square2MouseReleased(evt);
            }
        });
        boardPanel.add(square2);

        square3.setText(" ");
        square3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square3MouseReleased(evt);
            }
        });
        boardPanel.add(square3);

        square4.setBackground(new java.awt.Color(153, 153, 153));
        square4.setText(" ");
        square4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square4MouseReleased(evt);
            }
        });
        boardPanel.add(square4);

        square5.setText(" ");
        square5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square5MouseReleased(evt);
            }
        });
        boardPanel.add(square5);

        square6.setBackground(new java.awt.Color(153, 153, 153));
        square6.setText(" ");
        square6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square6MouseReleased(evt);
            }
        });
        boardPanel.add(square6);

        square7.setText(" ");
        square7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square7MouseReleased(evt);
            }
        });
        boardPanel.add(square7);

        square8.setBackground(new java.awt.Color(153, 153, 153));
        square8.setText(" ");
        square8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square8MouseReleased(evt);
            }
        });
        boardPanel.add(square8);

        square9.setBackground(new java.awt.Color(153, 153, 153));
        square9.setText(" ");
        square9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square9MouseReleased(evt);
            }
        });
        boardPanel.add(square9);

        square10.setText(" ");
        square10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square10MouseReleased(evt);
            }
        });
        boardPanel.add(square10);

        square11.setBackground(new java.awt.Color(153, 153, 153));
        square11.setText(" ");
        square11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square11MouseReleased(evt);
            }
        });
        boardPanel.add(square11);

        square12.setText(" ");
        square12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square12MouseReleased(evt);
            }
        });
        boardPanel.add(square12);

        square13.setBackground(new java.awt.Color(153, 153, 153));
        square13.setText(" ");
        square13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square13MouseReleased(evt);
            }
        });
        boardPanel.add(square13);

        square14.setText(" ");
        square14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square14MouseReleased(evt);
            }
        });
        boardPanel.add(square14);

        square15.setBackground(new java.awt.Color(153, 153, 153));
        square15.setText(" ");
        square15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square15MouseReleased(evt);
            }
        });
        boardPanel.add(square15);

        square16.setText(" ");
        square16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square16MouseReleased(evt);
            }
        });
        boardPanel.add(square16);

        square17.setText(" ");
        square17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square17MouseReleased(evt);
            }
        });
        boardPanel.add(square17);

        square18.setBackground(new java.awt.Color(153, 153, 153));
        square18.setText(" ");
        square18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square18MouseReleased(evt);
            }
        });
        boardPanel.add(square18);

        square19.setText(" ");
        square19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square19MouseReleased(evt);
            }
        });
        boardPanel.add(square19);

        square20.setBackground(new java.awt.Color(153, 153, 153));
        square20.setText(" ");
        square20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square20MouseReleased(evt);
            }
        });
        boardPanel.add(square20);

        square21.setText(" ");
        square21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square21MouseReleased(evt);
            }
        });
        boardPanel.add(square21);

        square22.setBackground(new java.awt.Color(153, 153, 153));
        square22.setText(" ");
        square22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square22MouseReleased(evt);
            }
        });
        boardPanel.add(square22);

        square23.setText(" ");
        square23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square23MouseReleased(evt);
            }
        });
        boardPanel.add(square23);

        square24.setBackground(new java.awt.Color(153, 153, 153));
        square24.setText(" ");
        square24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square24MouseReleased(evt);
            }
        });
        boardPanel.add(square24);

        square25.setBackground(new java.awt.Color(153, 153, 153));
        square25.setText(" ");
        square25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square25MouseReleased(evt);
            }
        });
        boardPanel.add(square25);

        square26.setText(" ");
        square26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square26MouseReleased(evt);
            }
        });
        boardPanel.add(square26);

        square27.setBackground(new java.awt.Color(153, 153, 153));
        square27.setText(" ");
        square27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square27MouseReleased(evt);
            }
        });
        boardPanel.add(square27);

        square28.setText(" ");
        square28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square28MouseReleased(evt);
            }
        });
        boardPanel.add(square28);

        square29.setBackground(new java.awt.Color(153, 153, 153));
        square29.setText(" ");
        square29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square29MouseReleased(evt);
            }
        });
        boardPanel.add(square29);

        square30.setText(" ");
        square30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square30MouseReleased(evt);
            }
        });
        boardPanel.add(square30);

        square31.setBackground(new java.awt.Color(153, 153, 153));
        square31.setText(" ");
        square31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square31MouseReleased(evt);
            }
        });
        boardPanel.add(square31);

        square32.setText(" ");
        square32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square32MouseReleased(evt);
            }
        });
        boardPanel.add(square32);

        square33.setText(" ");
        square33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square33MouseReleased(evt);
            }
        });
        boardPanel.add(square33);

        square34.setBackground(new java.awt.Color(153, 153, 153));
        square34.setText(" ");
        square34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square34MouseReleased(evt);
            }
        });
        boardPanel.add(square34);

        square35.setText(" ");
        square35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square35MouseReleased(evt);
            }
        });
        boardPanel.add(square35);

        square36.setBackground(new java.awt.Color(153, 153, 153));
        square36.setText(" ");
        square36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square36MouseReleased(evt);
            }
        });
        boardPanel.add(square36);

        square37.setText(" ");
        square37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square37MouseReleased(evt);
            }
        });
        boardPanel.add(square37);

        square38.setBackground(new java.awt.Color(153, 153, 153));
        square38.setText(" ");
        square38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square38MouseReleased(evt);
            }
        });
        boardPanel.add(square38);

        square39.setText(" ");
        square39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square39MouseReleased(evt);
            }
        });
        boardPanel.add(square39);

        square40.setBackground(new java.awt.Color(153, 153, 153));
        square40.setText(" ");
        square40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square40MouseReleased(evt);
            }
        });
        boardPanel.add(square40);

        square41.setBackground(new java.awt.Color(153, 153, 153));
        square41.setText(" ");
        square41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square41MouseReleased(evt);
            }
        });
        boardPanel.add(square41);

        square42.setText(" ");
        square42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square42MouseReleased(evt);
            }
        });
        boardPanel.add(square42);

        square43.setBackground(new java.awt.Color(153, 153, 153));
        square43.setText(" ");
        square43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square43MouseReleased(evt);
            }
        });
        boardPanel.add(square43);

        square44.setText(" ");
        square44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square44MouseReleased(evt);
            }
        });
        boardPanel.add(square44);

        square45.setBackground(new java.awt.Color(153, 153, 153));
        square45.setText(" ");
        square45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square45MouseReleased(evt);
            }
        });
        boardPanel.add(square45);

        square46.setText(" ");
        square46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square46MouseReleased(evt);
            }
        });
        boardPanel.add(square46);

        square47.setBackground(new java.awt.Color(153, 153, 153));
        square47.setText(" ");
        square47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square47MouseReleased(evt);
            }
        });
        boardPanel.add(square47);

        square48.setText(" ");
        square48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square48MouseReleased(evt);
            }
        });
        boardPanel.add(square48);

        square49.setText(" ");
        square49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square49MouseReleased(evt);
            }
        });
        boardPanel.add(square49);

        square50.setBackground(new java.awt.Color(153, 153, 153));
        square50.setText(" ");
        square50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square50MouseReleased(evt);
            }
        });
        boardPanel.add(square50);

        square51.setText(" ");
        square51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square51MouseReleased(evt);
            }
        });
        boardPanel.add(square51);

        square52.setBackground(new java.awt.Color(153, 153, 153));
        square52.setText(" ");
        square52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square52MouseReleased(evt);
            }
        });
        boardPanel.add(square52);

        square53.setText(" ");
        square53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square53MouseReleased(evt);
            }
        });
        boardPanel.add(square53);

        square54.setBackground(new java.awt.Color(153, 153, 153));
        square54.setText(" ");
        square54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square54MouseReleased(evt);
            }
        });
        boardPanel.add(square54);

        square55.setText(" ");
        square55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square55MouseReleased(evt);
            }
        });
        boardPanel.add(square55);

        square56.setBackground(new java.awt.Color(153, 153, 153));
        square56.setText(" ");
        square56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square56MouseReleased(evt);
            }
        });
        boardPanel.add(square56);

        square57.setBackground(new java.awt.Color(153, 153, 153));
        square57.setText(" ");
        square57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square57MouseReleased(evt);
            }
        });
        boardPanel.add(square57);

        square58.setText(" ");
        square58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square58MouseReleased(evt);
            }
        });
        boardPanel.add(square58);

        square59.setBackground(new java.awt.Color(153, 153, 153));
        square59.setText(" ");
        square59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square59MouseReleased(evt);
            }
        });
        boardPanel.add(square59);

        square60.setText(" ");
        square60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square60MouseReleased(evt);
            }
        });
        boardPanel.add(square60);

        square61.setBackground(new java.awt.Color(153, 153, 153));
        square61.setText(" ");
        square61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square61MouseReleased(evt);
            }
        });
        boardPanel.add(square61);

        square62.setText(" ");
        square62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square62MouseReleased(evt);
            }
        });
        boardPanel.add(square62);

        square63.setBackground(new java.awt.Color(153, 153, 153));
        square63.setText(" ");
        square63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square63MouseReleased(evt);
            }
        });
        boardPanel.add(square63);

        square64.setText(" ");
        square64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                square64MouseReleased(evt);
            }
        });
        boardPanel.add(square64);

        gameInfojLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gameInfojLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        newGamejButton.setText("New Game");
        newGamejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGamejButtonActionPerformed(evt);
            }
        });

        gameInfojLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameInfojLabel2.setText(" ");

        gameInfoLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameInfoLabel3.setText(" ");

        gameSelectJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Draughts", "Knights Tour", "Chess" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameInfojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(gameSelectJComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gameInfoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newGamejButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addComponent(gameInfojLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gameInfojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gameInfojLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gameInfoLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newGamejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gameSelectJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void square1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square1MouseReleased
        // TODO add your handling code here:
        mouseReleased(1);
    }//GEN-LAST:event_square1MouseReleased

    private void square2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square2MouseReleased
        // TODO add your handling code here:
        mouseReleased(2);
    }//GEN-LAST:event_square2MouseReleased

    private void square3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square3MouseReleased
        // TODO add your handling code here:
        mouseReleased(3);
    }//GEN-LAST:event_square3MouseReleased

    private void square4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square4MouseReleased
        // TODO add your handling code here:
        mouseReleased(4);
    }//GEN-LAST:event_square4MouseReleased

    private void square5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square5MouseReleased
        // TODO add your handling code here:
        mouseReleased(5);
    }//GEN-LAST:event_square5MouseReleased

    private void square6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square6MouseReleased
        // TODO add your handling code here:
        mouseReleased(6);
    }//GEN-LAST:event_square6MouseReleased

    private void square7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square7MouseReleased
        // TODO add your handling code here:
        mouseReleased(7);
    }//GEN-LAST:event_square7MouseReleased

    private void square8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square8MouseReleased
        // TODO add your handling code here:
        mouseReleased(8);
    }//GEN-LAST:event_square8MouseReleased

    private void square9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square9MouseReleased
        // TODO add your handling code here:
        mouseReleased(9);
    }//GEN-LAST:event_square9MouseReleased

    private void square10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square10MouseReleased
        // TODO add your handling code here:
        mouseReleased(10);
    }//GEN-LAST:event_square10MouseReleased

    private void square11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square11MouseReleased
        // TODO add your handling code here:
        mouseReleased(11);
    }//GEN-LAST:event_square11MouseReleased

    private void square12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square12MouseReleased
        // TODO add your handling code here:
        mouseReleased(12);
    }//GEN-LAST:event_square12MouseReleased

    private void square13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square13MouseReleased
        // TODO add your handling code here:
        mouseReleased(13);
    }//GEN-LAST:event_square13MouseReleased

    private void square14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square14MouseReleased
        // TODO add your handling code here:
        mouseReleased(14);
    }//GEN-LAST:event_square14MouseReleased

    private void square15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square15MouseReleased
        // TODO add your handling code here:
        mouseReleased(15);
    }//GEN-LAST:event_square15MouseReleased

    private void square16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square16MouseReleased
        // TODO add your handling code here:
        mouseReleased(16);
    }//GEN-LAST:event_square16MouseReleased

    private void square17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square17MouseReleased
        // TODO add your handling code here:
        mouseReleased(17);
    }//GEN-LAST:event_square17MouseReleased

    private void square18MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square18MouseReleased
        // TODO add your handling code here:
        mouseReleased(18);
    }//GEN-LAST:event_square18MouseReleased

    private void square19MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square19MouseReleased
        // TODO add your handling code here:
        mouseReleased(19);
    }//GEN-LAST:event_square19MouseReleased

    private void square20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square20MouseReleased
        // TODO add your handling code here:
        mouseReleased(20);
    }//GEN-LAST:event_square20MouseReleased

    private void square21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square21MouseReleased
        // TODO add your handling code here:
        mouseReleased(21);
    }//GEN-LAST:event_square21MouseReleased

    private void square22MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square22MouseReleased
        // TODO add your handling code here:
        mouseReleased(22);
    }//GEN-LAST:event_square22MouseReleased

    private void square23MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square23MouseReleased
        // TODO add your handling code here:
        mouseReleased(23);
    }//GEN-LAST:event_square23MouseReleased

    private void square24MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square24MouseReleased
        // TODO add your handling code here:
        mouseReleased(24);
    }//GEN-LAST:event_square24MouseReleased

    private void square25MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square25MouseReleased
        // TODO add your handling code here:
        mouseReleased(25);
    }//GEN-LAST:event_square25MouseReleased

    private void square26MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square26MouseReleased
        // TODO add your handling code here:
        mouseReleased(26);
    }//GEN-LAST:event_square26MouseReleased

    private void square27MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square27MouseReleased
        // TODO add your handling code here:
        mouseReleased(27);
    }//GEN-LAST:event_square27MouseReleased

    private void square28MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square28MouseReleased
        // TODO add your handling code here:
        mouseReleased(28);
    }//GEN-LAST:event_square28MouseReleased

    private void square29MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square29MouseReleased
        // TODO add your handling code here:
        mouseReleased(29);
    }//GEN-LAST:event_square29MouseReleased

    private void square30MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square30MouseReleased
        // TODO add your handling code here:
        mouseReleased(30);
    }//GEN-LAST:event_square30MouseReleased

    private void square31MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square31MouseReleased
        // TODO add your handling code here:
        mouseReleased(31);
    }//GEN-LAST:event_square31MouseReleased

    private void square32MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square32MouseReleased
        // TODO add your handling code here:#
        mouseReleased(32);
    }//GEN-LAST:event_square32MouseReleased

    private void square33MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square33MouseReleased
        // TODO add your handling code here:
        mouseReleased(33);
    }//GEN-LAST:event_square33MouseReleased

    private void square34MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square34MouseReleased
        // TODO add your handling code here:
        mouseReleased(34);
    }//GEN-LAST:event_square34MouseReleased

    private void square35MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square35MouseReleased
        // TODO add your handling code here:
        mouseReleased(35);
    }//GEN-LAST:event_square35MouseReleased

    private void square36MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square36MouseReleased
        // TODO add your handling code here:
        mouseReleased(36);
    }//GEN-LAST:event_square36MouseReleased

    private void square37MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square37MouseReleased
        // TODO add your handling code here:
        mouseReleased(37);
    }//GEN-LAST:event_square37MouseReleased

    private void square38MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square38MouseReleased
        // TODO add your handling code here:
        mouseReleased(38);
    }//GEN-LAST:event_square38MouseReleased

    private void square39MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square39MouseReleased
        // TODO add your handling code here:
        mouseReleased(39);
    }//GEN-LAST:event_square39MouseReleased

    private void square40MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square40MouseReleased
        // TODO add your handling code here:
        mouseReleased(40);
    }//GEN-LAST:event_square40MouseReleased

    private void square41MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square41MouseReleased
        // TODO add your handling code here:
        mouseReleased(41);
    }//GEN-LAST:event_square41MouseReleased

    private void square42MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square42MouseReleased
        // TODO add your handling code here:
        mouseReleased(42);
    }//GEN-LAST:event_square42MouseReleased

    private void square43MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square43MouseReleased
        // TODO add your handling code here:
        mouseReleased(43);
    }//GEN-LAST:event_square43MouseReleased

    private void square44MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square44MouseReleased
        // TODO add your handling code here:
        mouseReleased(44);
    }//GEN-LAST:event_square44MouseReleased

    private void square45MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square45MouseReleased
        // TODO add your handling code here:
        mouseReleased(45);
    }//GEN-LAST:event_square45MouseReleased

    private void square46MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square46MouseReleased
        // TODO add your handling code here:
        mouseReleased(46);
    }//GEN-LAST:event_square46MouseReleased

    private void square47MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square47MouseReleased
        // TODO add your handling code here:
        mouseReleased(47);
    }//GEN-LAST:event_square47MouseReleased

    private void square48MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square48MouseReleased
        // TODO add your handling code here:
        mouseReleased(48);
    }//GEN-LAST:event_square48MouseReleased

    private void square49MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square49MouseReleased
        // TODO add your handling code here:
        mouseReleased(49);
    }//GEN-LAST:event_square49MouseReleased

    private void square50MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square50MouseReleased
        // TODO add your handling code here:
        mouseReleased(50);
    }//GEN-LAST:event_square50MouseReleased

    private void square51MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square51MouseReleased
        // TODO add your handling code here:
        mouseReleased(51);
    }//GEN-LAST:event_square51MouseReleased

    private void square52MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square52MouseReleased
        // TODO add your handling code here:
        mouseReleased(52);
    }//GEN-LAST:event_square52MouseReleased

    private void square53MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square53MouseReleased
        // TODO add your handling code here:
        mouseReleased(53);
    }//GEN-LAST:event_square53MouseReleased

    private void square54MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square54MouseReleased
        // TODO add your handling code here:
        mouseReleased(54);
    }//GEN-LAST:event_square54MouseReleased

    private void square55MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square55MouseReleased
        // TODO add your handling code here:
        mouseReleased(55);
    }//GEN-LAST:event_square55MouseReleased

    private void square56MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square56MouseReleased
        // TODO add your handling code here:
        mouseReleased(56);
    }//GEN-LAST:event_square56MouseReleased

    private void square57MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square57MouseReleased
        // TODO add your handling code here:
        mouseReleased(57);
    }//GEN-LAST:event_square57MouseReleased

    private void square58MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square58MouseReleased
        // TODO add your handling code here:
        mouseReleased(58);
    }//GEN-LAST:event_square58MouseReleased

    private void square59MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square59MouseReleased
        // TODO add your handling code here:
        mouseReleased(59);
    }//GEN-LAST:event_square59MouseReleased

    private void square60MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square60MouseReleased
        // TODO add your handling code here:
        mouseReleased(60);
    }//GEN-LAST:event_square60MouseReleased

    private void square61MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square61MouseReleased
        // TODO add your handling code here:
        mouseReleased(61);
    }//GEN-LAST:event_square61MouseReleased

    private void square62MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square62MouseReleased
        // TODO add your handling code here:
        mouseReleased(62);
    }//GEN-LAST:event_square62MouseReleased

    private void square63MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square63MouseReleased
        // TODO add your handling code here:
        mouseReleased(63);
    }//GEN-LAST:event_square63MouseReleased

    private void square64MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square64MouseReleased
        // TODO add your handling code here:
        mouseReleased(64);
    }//GEN-LAST:event_square64MouseReleased

    private void mouseReleased(int squareNum) {
        System.out.println("mouseReleasedint squareNum: " + squareNum);
        game.squareSelected(BOARD_BUTTONS, squareNum);
        game.paintBoard(BOARD_BUTTONS);
        updateGameStateMessages();
    }


    private void newGame() {
        String gameSelection = this.gameSelectJComboBox.getSelectedItem().toString();
        if (gameSelection.equalsIgnoreCase("Draughts")) {
            this.game = new Draughts();
        } else if (gameSelection.equalsIgnoreCase("Knights Tour")) {
//            this.game = new KnightsTour();
        } else if (gameSelection.equalsIgnoreCase("Chess")) {
            this.game = new Chess();
        }
        this.game.newGame();

        javax.swing.JButton[][] board_buttons_start = {{square1, square2, square3, square4, square5, square6, square7, square8},
                {square9, square10, square11, square12, square13, square14, square15, square16},
                {square17, square18, square19, square20, square21, square22, square23, square24},
                {square25, square26, square27, square28, square29, square30, square31, square32},
                {square33, square34, square35, square36, square37, square38, square39, square40},
                {square41, square42, square43, square44, square45, square46, square47, square48},
                {square49, square50, square51, square52, square53, square54, square55, square56},
                {square57, square58, square59, square60, square61, square62, square63, square64}
        };

        BOARD_BUTTONS = board_buttons_start;

        game.paintBoard(BOARD_BUTTONS);
        updateGameStateMessages();
    }

    private void newGamejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGamejButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("newGamejButtonActionPerformed");
        newGame();
        updateGameStateMessages();
    }//GEN-LAST:event_newGamejButtonActionPerformed

    private void updateGameStateMessages() {
        System.out.println("updateGameStateMessages");
        String[] gameStateMessages = game.getGameStateMessage();
        this.gameInfojLabel.setText(gameStateMessages[0]);
        this.gameInfojLabel2.setText(gameStateMessages[1]);
        this.gameInfoLabel3.setText(gameStateMessages[2]);

    }

    public static int[] convertSquareNumToCoords(int squareNum) {
        squareNum -= 1;
        int squareRow = squareNum / BoardGame.ROWCOUNT;
        int squareCol = squareNum % BoardGame.COLCOUNT;
        int[] coords = {squareRow, squareCol};

        System.out.println("convertSquareNumToCoords - squareNum : " + squareNum + " coords : " + Arrays.toString(coords));

        return coords;
    }

    public static int convertCoordsToSqNum(int[] coords) {
        int squareNum = 1;
        squareNum += (coords[0]) * BoardGame.COLCOUNT;
        squareNum += coords[1];

        System.out.println("convertCoordsToSqNum - squareNum : " + squareNum + " coords : " + Arrays.toString(coords));

        return squareNum;
    }

    public static boolean validCoords(int[] coords) {
        int rowCoord = coords[0];
        int colCoord = coords[1];

        boolean validRow = rowCoord < ROWCOUNT && (rowCoord >= 0);
        boolean validCol = colCoord < COLCOUNT && (colCoord >= 0);

        System.out.println("convertCoordsToSqNum - validRow : " + validRow + "validCol : "+validCol+" coords : " + Arrays.toString(coords));
        return validRow && validCol;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardGame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardPanel;
    private javax.swing.JLabel gameInfoLabel3;
    private javax.swing.JLabel gameInfojLabel;
    private javax.swing.JLabel gameInfojLabel2;
    private javax.swing.JComboBox<String> gameSelectJComboBox;
    private javax.swing.JButton newGamejButton;
    private javax.swing.JButton square1;
    private javax.swing.JButton square10;
    private javax.swing.JButton square11;
    private javax.swing.JButton square12;
    private javax.swing.JButton square13;
    private javax.swing.JButton square14;
    private javax.swing.JButton square15;
    private javax.swing.JButton square16;
    private javax.swing.JButton square17;
    private javax.swing.JButton square18;
    private javax.swing.JButton square19;
    private javax.swing.JButton square2;
    private javax.swing.JButton square20;
    private javax.swing.JButton square21;
    private javax.swing.JButton square22;
    private javax.swing.JButton square23;
    private javax.swing.JButton square24;
    private javax.swing.JButton square25;
    private javax.swing.JButton square26;
    private javax.swing.JButton square27;
    private javax.swing.JButton square28;
    private javax.swing.JButton square29;
    private javax.swing.JButton square3;
    private javax.swing.JButton square30;
    private javax.swing.JButton square31;
    private javax.swing.JButton square32;
    private javax.swing.JButton square33;
    private javax.swing.JButton square34;
    private javax.swing.JButton square35;
    private javax.swing.JButton square36;
    private javax.swing.JButton square37;
    private javax.swing.JButton square38;
    private javax.swing.JButton square39;
    private javax.swing.JButton square4;
    private javax.swing.JButton square40;
    private javax.swing.JButton square41;
    private javax.swing.JButton square42;
    private javax.swing.JButton square43;
    private javax.swing.JButton square44;
    private javax.swing.JButton square45;
    private javax.swing.JButton square46;
    private javax.swing.JButton square47;
    private javax.swing.JButton square48;
    private javax.swing.JButton square49;
    private javax.swing.JButton square5;
    private javax.swing.JButton square50;
    private javax.swing.JButton square51;
    private javax.swing.JButton square52;
    private javax.swing.JButton square53;
    private javax.swing.JButton square54;
    private javax.swing.JButton square55;
    private javax.swing.JButton square56;
    private javax.swing.JButton square57;
    private javax.swing.JButton square58;
    private javax.swing.JButton square59;
    private javax.swing.JButton square6;
    private javax.swing.JButton square60;
    private javax.swing.JButton square61;
    private javax.swing.JButton square62;
    private javax.swing.JButton square63;
    private javax.swing.JButton square64;
    private javax.swing.JButton square7;
    private javax.swing.JButton square8;
    private javax.swing.JButton square9;
    // End of variables declaration//GEN-END:variables

    public Game game;
    public javax.swing.JButton[][] BOARD_BUTTONS;

    static int ROWCOUNT = 8;
    static int COLCOUNT = 8;

}
